"""C-backed Farrar's striped Smith-Waterman via cffi, using the Complete
Striped Smith-Waterman Library (SSW, vendored as a git submodule) as the
underlying kernel instead of simulating the striped method in Python (see
../farrar/__init__.py for that simulation).

pen layout: array.array('b', [match, mismatch, del_open, del_ext, ins_open, ins_ext])
match/mismatch are pre-negated, same convention as every other implementation
in this repo (see scalar.py's score_pair()).

SSW only has one affine gap cost, applied to both insertions and deletions --
unlike our own Penalties struct, it has no separate ins_open/ins_ext. Rather
than silently aligning with the wrong cost when del_open != ins_open or
del_ext != ins_ext, CFarrarImpl checks this up front in run() and refuses to
call into SSW at all if the penalties don't match what it supports.
"""

from __future__ import annotations

import array
import os
import sys

from cffi import FFI

from ...types import Aligner, AlignmentResult, Recorder, TracebackResult

_here = os.path.dirname(os.path.abspath(__file__))
_SSW_SRC = os.path.join(_here, "Complete-Striped-Smith-Waterman-Library", "src")

# BAM-style cigar op codes SSW's raw ssw_align() output uses (see MAPSTR in
# ssw.h) -- mapped onto the same "diag"/"left"/"up" vocabulary
# traceback_alignment() in scalar.py uses, so a TracebackResult's `path`
# means the same thing regardless of which implementation produced it.
#   M (0): consumes one query char + one reference char -> diag
#   I (1): consumes one query char only (insertion vs. reference)  -> up
#   D (2): consumes one reference char only (deletion vs. reference) -> left
_CIGAR_OP_TO_DIRECTION = {0: "diag", 1: "up", 2: "left"}


def _build_lib():
    """Compile ssw_wrap.c + the vendored SSW library's ssw.c into the shared
    _ssw_ffi extension and import it.

    Build/import is deferred to instantiation time -- same reasoning as
    c_scalar's _build_lib(): only the implementation actually selected via
    --implementation gets compiled. Uses its own module name (_ssw_ffi, not
    c_scalar's _swag_ffi) since this is a completely different ABI -- no
    reason to share c_scalar's sys.modules eviction dance for an unrelated
    header.
    """
    ffibuilder = FFI()

    # cdef() is a pure C declaration parser -- it cannot handle preprocessor
    # directives. Read ssw_wrap.h but strip any line starting with '#'
    # before passing; the declarations themselves parse fine.
    _h_path = os.path.join(_here, "ssw_wrap.h")
    with open(_h_path) as f:
        _header_decls = "\n".join(
            line for line in f if not line.lstrip().startswith("#")
        )
    ffibuilder.cdef(_header_decls)

    ffibuilder.set_source(
        "_ssw_ffi",
        """
        #include "ssw_wrap.h"
        """,
        sources=[
            os.path.join(_here, "ssw_wrap.c"),
            os.path.join(_SSW_SRC, "ssw.c"),
        ],
        include_dirs=[_here, _SSW_SRC],
        extra_compile_args=["-O3", "-march=native"],
    )

    try:
        ffibuilder.compile(tmpdir="./", verbose=False)
    except OSError as exc:
        raise ImportError("c_farrar: failed to compile ssw_wrap.c / ssw.c") from exc

    if _here not in sys.path:
        sys.path.insert(0, _here)

    sys.modules.pop("_ssw_ffi", None)
    import _ssw_ffi  # noqa: E402 -- generated by ffibuilder.compile() above
    return _ssw_ffi.lib, _ssw_ffi.ffi


class CFarrarImpl(Aligner):
    """C-backed Farrar's striped Smith-Waterman implementation, using SSW as
    the kernel.

    best_cell_only maps directly onto SSW's own internal pass structure:
    ssw_align() always runs a forward striped SIMD pass for score + end
    position; best_cell_only=True stops there (wantTraceback=0). When False,
    it also runs SSW's reverse pass (begin position) and a banded-DP pass
    that produces a real CIGAR, decoded here into a TracebackResult per pair
    -- so unlike every other implementation in this repo, c_farrar's full
    traceback is the *default* path, not an opt-in second pass.
    """

    def __init__(self, verbose: int = 0, best_cell_only: bool = False) -> None:
        self.verbose = verbose
        self.best_cell_only = best_cell_only
        self.rec = Recorder(verbose=verbose)
        self.results: list[AlignmentResult] = []
        self.pair_recs: list[Recorder] = []
        self.tracebacks: list[TracebackResult | None] = []
        self._lib, self._ffi = _build_lib()

    @staticmethod
    def _check_gap_penalties(pen: array.array) -> None:
        """SSW has one affine gap cost applied to both directions -- no
        separate ins_open/ins_ext. Refuse to run at all (rather than align
        with the wrong cost) if the caller asked for asymmetric penalties.
        """
        _match, _mismatch, del_open, del_ext, ins_open, ins_ext = pen
        if del_open != ins_open or del_ext != ins_ext:
            raise SystemExit(
                "c_farrar: SSW only supports one affine gap cost applied to "
                "both insertions and deletions, but --penalties gave "
                f"del_open={del_open} ins_open={ins_open} and "
                f"del_ext={del_ext} ins_ext={ins_ext}. Use matching "
                "del/ins penalties (e.g. the default -2,1,3,1,3,1), or pick "
                "a different --implementation."
            )

    def _decode_cigar(
        self, cigar_ints, cigar_len: int, qry_begin: int, ref_begin: int,
        qseq: str, rseq: str,
    ) -> TracebackResult:
        """Walk SSW's cigar (already in alignment-start-to-end order, unlike
        scalar.py's traceback which walks backward and reverses at the end)
        into the same TracebackResult shape every other implementation uses.
        """
        aligned_query: list[str] = []
        aligned_reference: list[str] = []
        path: list[str] = []
        qi, ri = qry_begin, ref_begin

        for k in range(cigar_len):
            raw = cigar_ints[k]
            op = raw & 0xF
            length = raw >> 4
            direction = _CIGAR_OP_TO_DIRECTION[op]
            for _ in range(length):
                if direction == "diag":
                    aligned_query.append(qseq[qi])
                    aligned_reference.append(rseq[ri])
                    qi += 1
                    ri += 1
                elif direction == "up":
                    aligned_query.append(qseq[qi])
                    aligned_reference.append("-")
                    qi += 1
                else:  # "left"
                    aligned_query.append("-")
                    aligned_reference.append(rseq[ri])
                    ri += 1
                path.append(direction)

        return TracebackResult(
            start_query=qry_begin + 1,
            start_reference=ref_begin + 1,
            aligned_query="".join(aligned_query),
            aligned_reference="".join(aligned_reference),
            path=tuple(path),
        )

    def _align_batch(self, pen: array.array) -> None:
        """Align a batch of reference/query pairs via SSW.

        Unlike c_scalar/hip_diagonal, pairs don't need to be padded to a
        common length -- each pair gets its own independent ssw_init() call
        C-side, so refSeqs/qrySeqs are just concatenated with no padding and
        refLens/qryLens carry each pair's real length.
        """
        self._check_gap_penalties(pen)
        num_pairs = len(self.pairs)
        want_traceback = not self.best_cell_only

        ref_bytes = b"".join(rseq.encode("ascii") for _qn, _qs, _rn, rseq in self.pairs)
        qry_bytes = b"".join(qseq.encode("ascii") for _qn, qseq, _rn, _rseq in self.pairs)
        ref_lens = self._ffi.new("int32_t[]", [len(rseq) for _qn, _qs, _rn, rseq in self.pairs])
        qry_lens = self._ffi.new("int32_t[]", [len(qseq) for _qn, qseq, _rn, _rseq in self.pairs])

        penalties = self._ffi.new("const struct Penalties*", list(pen))[0]
        best_cell = self._ffi.new("struct bestCell[]", num_pairs)
        tracebacks = (
            self._ffi.new("struct sswTraceback[]", num_pairs)
            if want_traceback
            else self._ffi.NULL
        )

        with self.rec.timed("smith_waterman.dp_fill"):
            self._lib.alignBatchSSW(
                penalties,
                ref_bytes, ref_lens,
                qry_bytes, qry_lens,
                num_pairs, int(want_traceback),
                best_cell, tracebacks,
            )

        try:
            for np in range(num_pairs):
                self.pair_recs.append(Recorder())
                self.results.append(
                    AlignmentResult(best_cell[np].score, best_cell[np].row, best_cell[np].col)
                )

                if not want_traceback:
                    self.tracebacks.append(None)
                    continue

                _qname, qseq, _rname, rseq = self.pairs[np]
                tb = tracebacks[np]
                if tb.cigar == self._ffi.NULL or tb.cigarLen == 0:
                    self.tracebacks.append(None)
                    continue
                self.tracebacks.append(
                    self._decode_cigar(
                        tb.cigar, tb.cigarLen, tb.qryBegin - 1, tb.refBegin - 1,
                        qseq, rseq,
                    )
                )
        finally:
            if want_traceback:
                self._lib.freeSSWTraceback(tracebacks, num_pairs)

    def run(self, pen: array.array) -> None:
        self._align_batch(pen)
