"""C-backed scalar Smith-Waterman via cffi (compiled from scalar.c / swag.h).

pen layout: array.array('b', [match, mismatch, del_open, del_ext, ins_open, ins_ext])
match/mismatch are pre-negated; all six values are passed directly through
as the penalties[6] array.
"""

from __future__ import annotations

import array
import os
import sys

from cffi import FFI

from ..types import Aligner, AlignmentResult, Recorder

_here = os.path.dirname(os.path.abspath(__file__))


def _build_lib():
    """Compile scalar.c into the shared _swag_ffi extension and import it.

    _swag_ffi is the same module name c_farrar.py builds (both share swag.h's
    ABI, just backed by a different .c file). Build/import is deferred to
    instantiation time — rather than module-import time — so only the
    implementation actually selected via --implementation gets compiled and
    loaded; doing it eagerly at import time raced c_farrar's build for the
    sys.modules["_swag_ffi"] slot regardless of which one was chosen.
    """
    ffibuilder = FFI()

    # cdef() is a pure C declaration parser — it cannot handle preprocessor
    # directives.  Read swag.h but strip any line starting with '#' before
    # passing; the declarations themselves parse fine.
    _h_path = os.path.join(_here, "swag.h")
    with open(_h_path) as f:
        _header_decls = "\n".join(
            line for line in f if not line.lstrip().startswith("#")
        )
    ffibuilder.cdef(_header_decls)

    # set_source produces the C translation unit the compiler sees; full #includes
    # are fine here.  Use absolute paths so the build works from any cwd.
    ffibuilder.set_source(
        "_swag_ffi",
        """
        #include <stdint.h>
        #include <stddef.h>
        #include <stdlib.h>
        #include "swag.h"
        #include <time.h>
        #include <stdio.h>
        """,
        sources=[os.path.join(_here, "scalar.c")],
        include_dirs=[_here],
        extra_compile_args=["-O3", "-march=native"],
    )

    try:
        ffibuilder.compile(tmpdir="./", verbose=False) # FIX: setting tmpdir to _here seems to create a new path inside of file's directory
    except OSError as exc:
        raise ImportError("c_scalar: failed to compile scalar.c") from exc

    # The compiled extension lands in _here; add it to sys.path so Python finds it.
    if _here not in sys.path:
        sys.path.insert(0, _here)

    # Drop any _swag_ffi already cached in sys.modules (e.g. from c_farrar)
    # so this import loads the extension we just compiled, not a stale one.
    sys.modules.pop("_swag_ffi", None)
    import _swag_ffi  # noqa: E402 — generated by ffibuilder.compile() above
    return _swag_ffi.lib, _swag_ffi.ffi


class CScalarImpl(Aligner):
    """C-backed scalar Smith-Waterman implementation."""

    def __init__(self, verbose: int = 0) -> None:
        self.verbose = verbose
        self.rec = Recorder(verbose=verbose)
        self.results: list[AlignmentResult] = []
        self.pair_recs: list[Recorder] = []
        self._lib, self._ffi = _build_lib()

    def _align_batch(self, pen: array.array) -> None:
        """Align a batch of reference and query pairs via the C kernel.
        Packs all of the sequences and matrices together before passing into C kernel
        Best score of each pair is stored

        Records/Copies back into recorders
        WARNING: Post score calculation traceback can be done.. but it's not
        WARNING: Assumes lengths of all queries are the same
        WARNING: Assumes lengths of all references are the same
        """
        # Getting elements from class attributes
        num_pairs = len(self.pairs)

        # This can be edited by dev for profiling
        N_FLOAT_COUNTERS = 0; # for example 1 or num_pairs and timing every pair in C code
        N_INT_COUNTERS = 0
        # Useful for storing info about matrices like timing and counters
        float_counters = self._ffi.new("float[]", N_FLOAT_COUNTERS) if N_FLOAT_COUNTERS > 0 else self._ffi.NULL
        int_counters = self._ffi.new("int[]", N_INT_COUNTERS) if N_INT_COUNTERS > 0 else self._ffi.NULL


        # padded lenngths, takes first item assumes all are the same length
        ref_len_c = len(self.pairs[0][3]) + 1
        qry_len_c = len(self.pairs[0][1]) + 1
        ref_bytes = b''.join(b'\x00' + str(pair[3]).encode('ascii') for pair in self.pairs)
        qry_bytes = b''.join(b'\x00' + str(pair[1]).encode('ascii') for pair in self.pairs)

        # index by 0 to make it clear we're passing the value, not the pointer.
        penalties = self._ffi.new("const struct Penalties*", list(pen))[0]
        best_cell = self._ffi.new("struct bestCell[]", num_pairs)
        H_buf = self._ffi.new("int16_t[]", num_pairs * qry_len_c * ref_len_c)
        E_buf = self._ffi.new("int16_t[]", num_pairs * qry_len_c * ref_len_c)
        F_buf = self._ffi.new("int16_t[]", num_pairs * qry_len_c * ref_len_c)

        with self.rec.timed("smith_waterman.dp_fill"):
            self._lib.alignBatch(
                num_pairs, ref_len_c, qry_len_c, penalties, ref_bytes, qry_bytes,
                H_buf, E_buf, F_buf, best_cell,
                float_counters, N_FLOAT_COUNTERS,
                int_counters, N_INT_COUNTERS,
            )
        # Another way to bring timings/counters but assuming the C code counted it
        #if N_FLOAT_COUNTERS > 0:
        #    self.rec.add_time("smith_waterman.dp_fill", float_counters[0])



        # Record final corrected H values for this column as h_matrix cell events.
        # It's just a copy into a Recorder
        for np in range(num_pairs):
            pair_rec = Recorder()
            h_offset = np * ref_len_c * qry_len_c
            res_offset =  ref_len_c * qry_len_c
            for i in range(ref_len_c):
                for j in range(qry_len_c):
                    pair_rec.add_cell_event("h_matrix", j, i, H_buf[h_offset+j*ref_len_c+i])
            self.pair_recs.append(pair_rec)
            self.results.append(AlignmentResult(best_cell[np].score, best_cell[np].row, best_cell[np].col))


    # FUNCTION DEPRECATED IN FAVOR OF BATCHING
    # Since C implementations are meant to run faster the preferred method is to run in a batch.
    def _align_one(self, pair_index: int, pen: array.array) -> None:
        """Align one pair via the C kernel.

        Records one "h_matrix" cell event per filled cell into rec.
        """
        # Getting elements from class attributes
        qname, qseq, rname, rseq = self.pairs[pair_index]

        # This can be edited by dev for profiling
        N_FLOAT_COUNTERS = 0; # for example 1 or num_pairs and timing every pair in C code
        N_INT_COUNTERS = 0
        # Useful for storing info about matrices like timing and counters
        float_counters = self._ffi.new("float[]", N_FLOAT_COUNTERS) if N_FLOAT_COUNTERS > 0 else self._ffi.NULL
        int_counters = self._ffi.new("int[]", N_INT_COUNTERS) if N_INT_COUNTERS > 0 else self._ffi.NULL

        pair_rec = Recorder()

        # padded lenngths
        ref_len_c = len(rseq) + 1
        qry_len_c = len(qseq) + 1
        ref_bytes = b'\x00' + rseq.encode('ascii')
        qry_bytes = b'\x00' + qseq.encode('ascii')

        penalties = self._ffi.new("const struct Penalties*", list(pen))[0]
        best_cell = self._ffi.new("struct bestCell *", [0, 0, 0]) # iniatilize bestCell to 0
        H_buf = self._ffi.new("int16_t[]", qry_len_c * ref_len_c)
        E_buf = self._ffi.new("int16_t[]", qry_len_c * ref_len_c)
        F_buf = self._ffi.new("int16_t[]", qry_len_c * ref_len_c)

        with pair_rec.timed("smith_waterman.dp_fill"):
            self._lib.alignOne(
                ref_len_c, qry_len_c, penalties, ref_bytes, qry_bytes,
                H_buf, E_buf, F_buf, best_cell,
                float_counters, N_FLOAT_COUNTERS,
                int_counters, N_INT_COUNTERS,
            )
        # Unless this code is changed nothing is done with float_counters and int_counters

        self.results.append(AlignmentResult(best_cell.score, best_cell.row, best_cell.col))
        self.pair_recs.append(pair_rec)


        # Record final corrected H values for this column as h_matrix cell events.
        # It's just a copy into a Recorder
        for i in range(ref_len_c):
            for j in range(qry_len_c):
                pair_rec.add_cell_event("h_matrix", j, i, H_buf[j*ref_len_c+i])

        self.rec.add_time("smith_waterman.dp_fill", pair_rec.times.get("smith_waterman.dp_fill", 0.0))

    def run(self, pen: array.array) -> None:
        self._align_batch(pen)

        # This code runs as a previous and working replacement to run(), but loops the multiple 
        # sequences through python instead of C calling C's align_one()
        # we know the size by now, we're starting the references here
        # for index in range(len(self.pairs)):
        #     self._align_one(index, pen)
