#ifndef  KSEQPP_CONFIG_HPP__
#define  KSEQPP_CONFIG_HPP__

#define KSEQPP_PROJECT_VERSION "4.0.0"
#define KSEQPP_PROJECT_VERSION_MAJOR "4"
#define KSEQPP_PROJECT_VERSION_MINOR "0"
#define KSEQPP_PROJECT_VERSION_PATCH "0"

#endif
